Document: sparql2nl
Title: Debian sparql2nl Manual
Author: <insert document author here>
Abstract: This manual describes what sparql2nl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sparql2nl/sparql2nl.sgml.gz

Format: postscript
Files: /usr/share/doc/sparql2nl/sparql2nl.ps.gz

Format: text
Files: /usr/share/doc/sparql2nl/sparql2nl.text.gz

Format: HTML
Index: /usr/share/doc/sparql2nl/html/index.html
Files: /usr/share/doc/sparql2nl/html/*.html
